# Generated by Django 3.0.3 on 2021-01-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Astro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
